Portal.UI/Controllers/UserControlController.cs
using Newtonsoft.Json;
using Portal.Core.Entidades.Universal;
using Portal.Core.Parametros.UserControl;
using Portal.Core.Repositorios.GerenciamentoFiscal;
using Portal.Core.Repositorios.Universal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portal.UI.Controllers
{
    public class UserControlController : Controller
    {
        private readonly irptEstado _rptEstado = new rptEstado();
        private readonly irptEstabelecimento _rptEstabelecimento = new rptEstabelecimento();
        private readonly irptImposto _rptImposto = new rptImposto();
        private readonly irptObrigacao _rptObrigacao = new rptObrigacao();
            
        // GET: UserControl
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult DropDownListEstado(pUserControlBase parametros)
        {
            ViewBag.Estado = _rptEstado.Obter();

            return PartialView("~/Views/_UserControl/_Estado.cshtml", parametros);
        }

        [ChildActionOnly]
        public PartialViewResult DropDownListEstabelecimento(pUserControlBase parametros)
        {
            ViewBag.Estabelecimento = _rptEstabelecimento.Obter();

            return PartialView("~/Views/_UserControl/_Estabelecimento.cshtml", parametros);
        }

        public String ObterImpostos ()
        {
            return JsonConvert.SerializeObject(_rptImposto.Obter().Where(a=> new[] { 6, 7, 8, 9, 11 }.Contains(a.ID)), Formatting.None);
        }

        public String ObterEstados()
        {
            return JsonConvert.SerializeObject(_rptEstado.Obter(), Formatting.None);
        }

        public String ObterObrigacoesFiscais()
        {
            return JsonConvert.SerializeObject(_rptObrigacao.Obter(), Formatting.None);
        }

        public String ObterEstabelecimentos()
        {
            return JsonConvert.SerializeObject(_rptEstabelecimento.Obter(), Formatting.None);
        }

        protected override void Dispose(bool disposing)
        {
            _rptEstado.Dispose();
            _rptEstabelecimento.Dispose();
        }
    }
}

Portal.UI/Views/_UserControl/_CalendarioFinal.cshtml
@{ 
    var TamCol = (int)ViewData["Col"];
}

<div class="col-lg-@TamCol">
    <div class="form-group">
        <label class="form-group-label">Data Final:</label>
        <div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text rounded-left"><i class="far fa-calendar-alt"></i></span></div>
            @Html.TextBox("DataFinal", DateTime.Today.ToShortDateString(), new { @id = "CalendFim", @class = "form-control rounded-right", @ng_model = "DataFinal" })
        </div>
    </div>
</div>

Portal.UI/Views/_UserControl/_CalendarioInicial.cshtml
@{
    var TamCol = (int)ViewData["Col"];
}

<div class="col-lg-@TamCol">
    <div class="form-group">
        <label class="form-group-label">Data Inicial:</label>
        <div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text rounded-left"><i class="far fa-calendar-alt"></i></span></div>
            @Html.TextBox("DataInicial", DateTime.Today.ToShortDateString(), new { @id = "CalendIni", @class = "form-control rounded-right", @ng_model = "DataInicial" })
        </div>
    </div>
</div>

Portal.UI/Views/_UserControl/_Estabelecimento.cshtml
@model Portal.Core.Parametros.UserControl.pUserControlBase

<div class="col-lg-@Model.Col">
    <div class="form-group">
        <label class="form-group-label">Estabelecimento:</label>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text rounded-left"><i class="fas fa-store-alt"></i></span>
            </div>
            @Html.DropDownList("Estabelecimento", new MultiSelectList(ViewBag.Estabelecimento, "ID", "DESC_ESTAB"), new { @class = "form-control selectpicker rounded-right", @multiple = "multiple", data_selected_text_format = "count", @data_actions_box = "true", @data_live_search = "true", @ng_model = "Estabelecimento" })
        </div>
    </div>
</div>

Portal.UI/Views/_UserControl/_Estado.cshtml
@model Portal.Core.Parametros.UserControl.pUserControlBase

<div class="col-lg-@Model.Col">
    <div class="form-group">
        <label class="form-group-label">Estado:</label>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text rounded-left"><i class="fas fa-map-marker-alt"></i></span>
            </div>
            @Html.DropDownList("UF", new MultiSelectList(ViewBag.Estado, "ID", "NOME"), new { @class = "form-control selectpicker rounded-right", @multiple = "multiple", data_selected_text_format = "count", @data_actions_box = "true", @data_live_search = "true", @ng_model = "UF" })
        </div>
    </div>
</div>

Portal.UI/Views/_UserControl/_Filtro.cshtml
@{
    string LocalFiltro = (string)ViewData["LocalFiltro"];
}

<div class="row">
    <div class="col-lg-11">
        <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#Filtro" role="tab" aria-controls="Filtro" aria-selected="true">
                    <i class="fa fa-filter"></i>&ensp; Filtro
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#Avancado" role="tab" aria-controls="Avancado" aria-selected="false">
                    <i class="fab fa-codepen"></i>&ensp; Avançado
                </a>
            </li>
            @*<li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#Database" role="tab" aria-controls="Database" aria-selected="false">
                        <i class="fas fa-database"></i>&ensp; Database
                    </a>
                </li>*@
        </ul>
        <div class="tab-content">
            <br />
            <div class="tab-pane fade show active" id="Filtro" role="tabpanel">
                <div class="container-fluid">
                    <div class="row">
                        @Html.Action("DropDownListEstado", "UserControl", new { Col = 2 })

                        @Html.Action("DropDownListEstabelecimento", "UserControl", new { Col = 4 })

                        @Html.Partial("~/Views/_UserControl/_CalendarioInicial.cshtml", new ViewDataDictionary(ViewData) { { "Col", 3 } })

                        @Html.Partial("~/Views/_UserControl/_CalendarioFinal.cshtml", new ViewDataDictionary(ViewData) { { "Col", 3 } })
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="Avancado" role="tabpanel">
                <div class="row">
                    <div class="container-fluid">
                        @Html.Partial("~/Views/" + @LocalFiltro + "/_FiltroAvancado.cshtml")
                    </div>
                </div>
            </div>
            @*<div class="tab-pane fade" id="Database" role="tabpanel">
                <div class="container-fluid">

                </div>
            </div>*@
        </div>
    </div>
    <div class="col-lg-1 d-flex align-items-end flex-column">
        <button type="submit"
                class="btn btn-primary mb-auto p-12">
            <i class="fa fa-search"></i>
        </button>

        <button type="button"
                class="btn btn-dark p-12">
            <i class="far fa-chart-bar"></i>
        </button>

        <button type="button"
                class="btn btn-dark mt-auto p-12"
                id="dropdownExportar"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
            <i class="fas fa-download"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownExportar">
            <a href="#" class="dropdown-item" ng-click="ExportarTxt()"><i class="far fa-file-alt"></i>&ensp; Texto</a>
            <a href="#" class="dropdown-item" ng-click="ExportarExcel()"><i class="far fa-file-excel"></i>&ensp; Excel</a>
            <a href="#" class="dropdown-item" ng-click="ExportarPdf()"><i class="far fa-file-pdf">&ensp; PDF</i></a>
        </div>
    </div>
</div>